default:
  script_dir: "where_the_scripts_from_github_are_stored/"
  scz_file_foldername: "where_the_files_from_GEO_are_stored/"
  output_file_dir: "where_you_want_your_result_file/"
  scz_variant_statistics_filename: "variant_statistics.txt.gz"
  scz_dna_count_filepath: "MPRA_SCZ_DNA_bcreads.txt.gz" 
  bc_file_pattern: "Pooled_.*\\_bcreads.txt"
  read_file_function_scriptname: "reading_functions.R"
  reproducibility_function_scriptname: "reproducibility_plot_functions.R"
  create_count_matrix_functions_scriptname: "create_count_matrix_functions.R"
  scz_barcode_rda_filename: "barcode_SCZ_data.tsv.gz"
  scz_mpra_output_file: "scz_mpra_result.tsv"
  scz_dna_count_file: "DNA_count_matrix.tsv"
  scz_rna_count_file: "RNA_count_matrix.tsv"
